### ISSUE TITLE
Categories or Taxonomie not working

### ISSUE THREAD

**Issue by fmoctezuma** [cloudnativemx/website#2]
**Hi Cloudnativemx**

Found a small issue on the gohugo main site, when I click on one of the categories e.g (Post, Podcast, or Evento) Gohugo couldn't find the categories related to it sending a 403 error.

Could this be related with the _[taxonomies]_ param on the toml file ?
https://gohugo.io/content-management/taxonomies/

Regards!
Francisco Moctezuma

**Comment by domix** [comment]
It's working now.
https://cloudnative.mx/categories/anuncio/
